const confrences = [
  {
    id: 1,
    name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2025 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"IT",
  },
  {
    id: 2,
    name: "Иктисодий йуналиш ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "18 декабрь 2024 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Economy",
  },
  {
    id: 3,
    name: "Тасдик ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "25 декабрь 2024 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"Science",
  },
  {
    id: 4,
    name: "Товлан ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "18 ноябрь 2024 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"IT",
  },
  {
    id: 5,
    name: "Теран ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "16 ноябрь 2024 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Economy",
  },
  {
    id: 6,
    name: "Бахор ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6 ноябр 2026 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"Science",
  },
  {
    id: 7,
    name: "Жахон ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6 январь 2025 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"IT",
  },
  {
    id: 8,
    name: "Шарк ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "8 март 2024 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Economy",
  },
  {
    id: 9,
    name: "Зироат ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"Science",
  },
  {
    id: 10,
    name: "Амалий ва тасвирий санъат ҳамда дизайн йўналишидаги республика.яя",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"IT",
  },
  {
    id: 11,
    name: "Санъат Тасвирий ва амалий  ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Science",
  },
  {
    id: 12,
    name: "Хамда тасвирий ва амалий санъат  дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"Economy",
  },
  {
    id: 13,
    name: "Дизайн тасвирий ва амалий санъат ҳамда  йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"IT",
  },
  {
    id: 14,
    name: "Йўналишидаги Тасвирий ва амалий санъат ҳамда дизайн республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Economy",
  },
  {
    id:15,
    name: "Республика тасвирий ва амалий санъат ҳамда дизайн йўналишидаги.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Science",
  },
  {
    id: 16,
    name: "Таълим ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"IT",
  },
  {
    id: 17,
    name: "Тартиб ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"Economy",
  },
  {
    id: 18,
    name: "Тарих ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Science",
  },
  {
    id: 19,
    name: "Турон ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"IT",
  },
  {
    id: 20,
    name: "Теран ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Economy",
  },
  {
    id: 21,
    name: "Педогогик ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"false",
    category:"Science",
  },
  {
    id: 22,
    name: "Маънавий ва амалий санъат ҳамда дизайн йўналишидаги республика.яя",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"IT",
  },
  {
    id: 23,
    name: "Маърифат ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Economy",
  },
  {
    id: 24,
    name: "Олим ва амалий санъат ҳамда дизайн йўналишидаги республика.",
    mail: "frccsc@frccsc.ru",
    year: "6–8 октября 2022 г.",
    address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
    url: "http://www.frccsc.ru",
    status:"true",
    category:"Science",
  },
];
export default confrences;
