const congreses = [
    {
      id: 1,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 2,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 3,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 4,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 5,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 6,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 7,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 8,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 9,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 10,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.яя",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 11,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
    {
      id: 12,
      name: "Тасвирий ва амалий санъат ҳамда дизайн йўналишидаги республика.",
      mail: "frccsc@frccsc.ru",
      year: "6–8 октября 2022 г.",
      address: "Россия, 119333, г. Москва, ул. Вавилова, 44/2",
      url: "http://www.frccsc.ru",
      status:"true",
    },
  ];
  export default congreses;
  